server:
  port: 8090
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.127.131:3306/qbp
    username: qbp
    password: qbp
    # url: jdbc:mysql://localhost:3306/qbp
    # username: root
    # password: 252748377


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定mapper.xml文件位置
  type-aliases-package: com.questionbrushingplatform.pojo.entity #别名扫描包
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
  global-config:
    db-config:
      id-type: auto #主键策略，自增
      update-strategy: not_null #更新策略，只更新非空字段
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值
      logic-not-delete-value: 0 #逻辑未删除值


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

